name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Accept Android SDK licenses and install tools
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true
        sdkmanager "build-tools;33.0.2" "platforms;android-33"

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: android debug
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/*.apk
